version: '2'

services:

  vis:
    build:
      context: vis
    ports:
      - 3000:3000
    volumes:
      - ./vis:/app:z
    links:
      - d2r
      - loadsheets

  sqldb:
    image: mariadb:10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=solarsystem
      - MYSQL_USER=solar
      - MYSQL_PASSWORD=system
    volumes:
      - mariadb:/var/lib/mysql:z

  d2r:
    image: cloudfluff/d2r
    ports:
      - 2020:2020
    volumes:
      - ./data:/var/lib/d2rq:z
    environment:
      - D2R_BASEURI=http://localhost:3000/
    links:
      - sqldb

  loadsheets:
    build:
      context: sheets
    volumes:
      - ./data:/data:z
      - ./sheets:/usr/local/sheets:z
    ports:
      - 80:80
    links:
      - sqldb
    command: python loadData.py
    entrypoint: bash wait-for-it.sh sqldb:3306 -t 0 --

volumes:
  mariadb: